import Button from "../components/ui/Button";
import Container from "../components/layout/Container";
import Pill from "../components/ui/Pill";

const trustPoints = [
  "No custody of funds",
  "Connect exchange via API",
  "Built for serious traders",
];

const metrics = [
  { label: "PROBABILITY", value: "74%", valueClass: "text-2xl" },
  { label: "CONFIDENCE", value: "42%", valueClass: "text-2xl" },
  { label: "POSITION SIZE", value: "0.4191", valueClass: "text-xl" },
  { label: "STATUS", value: "Healthy", valueClass: "text-xl text-emerald-300" },
];

function MetricTile({ label, value, valueClass }: { label: string; value: string; valueClass: string }) {
  return (
    <div className="rounded-2xl bg-white/5 ring-1 ring-white/10 p-4">
      <div className="text-xs text-slate-400">{label}</div>
      <div className={`mt-1 font-bold text-white ${valueClass}`}>{value}</div>
    </div>
  );
}

function SignalPreviewCard() {
  return (
    <div className="rounded-[2.5rem] bg-white/5 ring-1 ring-white/12 p-4 shadow-[0_0_80px_rgba(255,255,255,0.06)]">
      <div className="rounded-[2rem] bg-slate-950/60 ring-1 ring-white/10 overflow-hidden">
        <div className="px-5 py-4 flex items-center justify-between border-b border-white/10">
          <div className="text-sm font-semibold text-white">LIVE SIGNALS</div>
          <Pill>BTC/USDT</Pill>
        </div>

        <div className="p-5 space-y-4">
          <div className="flex items-center justify-between">
            <Pill>BUY SIGNAL</Pill>
            <span className="text-xs text-slate-400">Updated 30m ago</span>
          </div>

          <div className="h-32 rounded-2xl bg-white/5 ring-1 ring-white/10 relative overflow-hidden">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(34,211,238,0.20),transparent_55%),radial-gradient(circle_at_70%_70%,rgba(52,211,153,0.18),transparent_55%)]" />
            <svg className="absolute inset-0" viewBox="0 0 400 200" preserveAspectRatio="none">
              <path
                d="M0,140 C60,120 80,160 140,140 C190,120 220,140 270,110 C320,80 350,90 400,60"
                fill="none"
                stroke="rgba(34,211,238,0.9)"
                strokeWidth="3"
              />
            </svg>
          </div>

          <div className="grid grid-cols-2 gap-3">
            {metrics.map((metric) => (
              <MetricTile key={metric.label} {...metric} />
            ))}
          </div>

          <div className="pt-1 text-xs text-slate-400">Demo UI • For illustration only</div>
        </div>
      </div>
    </div>
  );
}

export default function Hero() {
  return (
    <section
      id="home"
      className="relative min-h-[calc(100vh-86px)] flex items-center"
    >
      <Container className="py-6 md:py-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-center">
          <div>
            <div className="flex flex-wrap gap-2 mb-5">
              <Pill>ML-powered signals</Pill>
              <Pill>Real-time updates</Pill>
              <Pill>Risk filters</Pill>
            </div>

            <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-white leading-tight">
              Upgrade Your Crypto Trading with ML—Powered Signals
            </h1>
            <p className="mt-5 text-slate-300 leading-relaxed text-lg">
              Elevate your trading with live BUY & SELL signals generated by advanced machine learning, updated in
              real-time — with transparency you can verify.
            </p>

            <div className="mt-7 flex flex-wrap items-center gap-3">
              <Button>Start Free Trial</Button>
              <Button variant="secondary">Join Waitlist</Button>
            </div>

            <div className="mt-7 flex flex-wrap gap-3 text-sm text-slate-300">
              {trustPoints.map((point) => (
                <span key={point}>✅ {point}</span>
              ))}
            </div>
          </div>

          <div className="relative">
            <div className="absolute -top-10 -right-8 h-52 w-52 rounded-full bg-cyan-500/15 blur-3xl" />
            <div className="absolute -bottom-10 -left-8 h-52 w-52 rounded-full bg-orange-500/15 blur-3xl" />

            <SignalPreviewCard />

            <div className="absolute -top-6 left-8 rounded-2xl bg-emerald-500/15 ring-1 ring-emerald-500/25 px-4 py-2 text-emerald-200 font-semibold">
              BUY
            </div>
            {/* <div className="absolute top-6 right-8 rounded-2xl bg-orange-500/15 ring-1 ring-orange-500/25 px-4 py-2 text-orange-200 font-semibold">
              SELL
            </div> */}
          </div>
        </div>
      </Container>
    </section>
  );
}
